name: hris_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  path_provider: ^2.0.11
  skeletons: ^0.0.3
  syncfusion_flutter_signaturepad: ^20.3.50
  table_calendar: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
